FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    plotly \
    mysql-connector-python \
    sqlalchemy 
    
COPY Dashboard /app/dashboard

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/streamlit_dashboard.py", "--server.address=0.0.0.0"]
